### ISSUE TITLE
Compiler not watching @import files

### ISSUE THREAD

**Issue by robertarango** [mjvotaw/Coda-2-LESS-Compiler#13]
Having an issue where where files are not being watched. Adding all files to be watched just causes errors when trying to compile. Is there a specific setting that needs to be enabled for imported files to be watched and changed?

**Comment by mjvotaw** [comment]
Hmm, That's very strange. 

Whenever you add a file, the plugin should automatically parse it for any @import files, and track when you save them as well. Note that this won't pick up if a file is changed/saved outside of Coda.

Could you turn on verbose logging and try this again, and send me anything that gets logged in Console?
Also, what versions of Coda and OS X are you running?

**Comment by mjvotaw** [comment]
Hm it looks like you're right, it's definitely not looking at imported files. Well this is embarrassing. I'll get this fixed right away.

**Comment by mjvotaw** [comment]
I finally figured out to debug plugins in XCode, and of course the problem doesn't occur while it's being debugged, which means it's probably some sort of weird timey-wimey race condition.

**Comment by mjvotaw** [comment]
So it looks like it's an issue with how I'm using NSTask to run the Less compiler, and/or an issue with the Less compiler itself. Basically, NSTask doesn't always return all of the output from the compiler, and I'm having a hell of time figuring out how to make it consistently work.

I'm really not sure what to do at this point.

**Comment by mjvotaw** [comment]
Hey @robertarango I just uploaded a new version to the repository. Will you download it and try it out for me? I'm pretty certain I've got this fixed now. It seemed to be a combination of NSTask being slightly erratic and Less/Node doing something to make NSTask think it had finished before it really did.

**Comment by mjvotaw** [comment]
Alright, well I'm going to close this, as it seems to be working fine now. If not, please let me know!

**Comment by mjvotaw** [comment]
Alright, well I'm going to close this, as it seems to be working fine now. If not, please let me know!
