### ISSUE TITLE
file: DEPENDS left over on hd root

### ISSUE THREAD

**Issue by SebastianBeres** [mjvotaw/Coda-2-LESS-Compiler#15]
Hi,

Is there way to auto delete file DEPENDS which is created each compile?

S

**Comment by mjvotaw** [comment]
So this is getting created at the root directory for you? As far as I can tell, it usually ends up getting created inside the plugin's contents folder.  I'll have to look into it, something has changed in Less 2.0 that causes this file to get made. Calling lessc with --depends still requires you to include an output path, but I don't remember it actually writing anything to that path in Less 1.x. If I can't get it to stop creating the file in the first place, I can probably at least have it delete the resulting file.

**Comment by CreatizerHub** [comment]
I've noticed it's something new with latest versions of Coda. If it was created before I'm sure it got deleted before I could notice it exist.

**Comment by mjvotaw** [comment]
I just uploaded a new build, let me know if it solves this for you!

**Comment by SebastianBeres** [comment]
Thank you! I will check it and see if issue is gone.
