### ISSUE TITLE
Compile errors until npm install

### ISSUE THREAD

**Issue by paynoattn** [mjvotaw/Coda-2-LESS-Compiler#17]
This is probably dumb, but I was getting dependency compile errors until I did a:

sudo npm install -g less

before it would compile correctly. A dependency like this might be something you want to add to your documentation. For dumb people like me (or even dumber people who have never used node). 

I should mention I installed via the coda plugin page.

**Comment by mjvotaw** [comment]
That's strange, you shouldn't need to do any of that. I package a completely separate instance of node and of lessc in my plugin (that's why it's like 13 megs--most of that is node).

Are you sure you installed my plugin? There's a second Less compiler called CodaLess ( https://github.com/idmean/CodaLess ) that's also available from Coda's plugin page.

**Comment by paynoattn** [comment]
It might be because I already had an installation of node and it was looking in my /usr/lib/ for less. Where do you have installing less? I have both installed but only yours is activated on the project I'm working on.

**Comment by mjvotaw** [comment]
Everything should be in ~/Library/Application Support/Coda 2/Plug-ins/LESSCompile.codaplugin/Contents/Resources.
It doesn't try to install anything, it just keeps a separate instance of node and lessc in its Resources folder  and calls that directly. 

I believe you and I have a fairly similar setup. I have node installed at usr/local/lib, and I don't have any version of lessc installed globally. I went ahead and installed CodaLess alongside my plugin, and while it throws an error complaining about not being able to find lessc, my plugin still successfully compiles. 

If you don't mind, will you try uninstalling CodaLess and seeing if my plugin still doesn't work for you?

Oh, and it might not hurt to take a moment and read the Readme for my plugin ( https://github.com/mjvotaw/Coda-2-LESS-Compiler/blob/master/README.md ) just to make sure you've got it setup correctly.

**Comment by paynoattn** [comment]
Yeah, you're right, it was the other plugin. I uninstalled it and globally uninstalled less in my /usr/local/ and it still works just fine. My bad.
