### ISSUE TITLE
Coda crashes when installing

### ISSUE THREAD

**Issue by fratsloos** [mjvotaw/Coda-2-LESS-Compiler#21]
When installing the plugin on a clean install Yosemite on a MB Pro 8.1 Coda crashes. Coda keeps crashing when starting. Only after removing the plugin with Finder or moving the plugin to the 'Plugins (Disabled)' folder, Coda starts again.

Version
-
Coda version: 2.5.12
Plugin version: 1.2

Steps to reproduce
-
- Install Coda, downloaded from Panic website;
- Install LESSCompiler plugin version 1.2 from the Panic Plugin website;
- When installing Coda crashes.

To fix Coda:
- Go to Finder, open your Library using Go (press Alt);
- Go to Application support > Coda 2 > Plug-ins;
- Remove LESSCompile 2.codaplugin;
- Or move LESSCompile 2.codaplugin to the Plugins (Disabled) folder.

When the plugin is not active, Coda will start.

Workaround
-
I've found installing is still possible with the following method:
- Download 1.1.0 version of LessCompile plugin at https://github.com/mjvotaw/Coda-2-LESS-Compiler/releases;
- Copy plugin to the 'Plugins (Disabled)' folder;
- Start Coda;
- Go to Coda settings and activate the plugin.

At this point I got an update request from the plugin in Coda. I didn't update yet. First I tested the plugin by using it the normal way (add a less-file in Plug-ins > LESS Compiler > Site Settings, and then save the file).

After that I updated the plugin using Settings > Plug-ins in Coda. The plugin updated to version 1.2 and Coda didn't crash.

**Comment by mjvotaw** [comment]
Looks like I wasn't checking to make sure the `.LESS Compiler` directory existed before trying to save the CoreData file to it. 

1.2.1 takes care of this. Thanks for the report!
