### ISSUE TITLE
Remote files possible?

### ISSUE THREAD

**Issue by mrJakez** [mjvotaw/Coda-2-LESS-Compiler#22]
Hi,

I found your plugin and like the idea that coda will be responsible to compile the less files itself. Currently a lot of my projects are remote only, but there seems to be an issue with these kind of less files.

Is there any chance to get this working? I mean compile the file locally on my Mac and automatically upload it to the specific directory on the remote host.

Or do I miss something?

Cheers
Dennis

**Comment by mjvotaw** [comment]
Editing a remote file isn't like editing something locally. When you edit a remote file, Coda makes a temporary copy of the file on your local machine and then uploads it to the remote server when you save. I don't have that ability as a plugin writer.

Frankly, I personally wouldn't feel comfortable writing a plugin that automatically creates and uploads a file to a remote server. I'm of the opinion that you should avoid directly editing remote files whenever possible, and instead work on changes locally before pushing them.

**Comment by mrJakez** [comment]
thx for that information :+1:
