### ISSUE TITLE
Plugin strips em units with undesired results

### ISSUE THREAD

**Issue by Calrion** [mjvotaw/Coda-2-LESS-Compiler#24]
I'm getting different results from the LESSCompile (v1.2.1) plugin for Coda (I'm using v2.5.16 (20417)) when compared with both the client-side JavaScript LESS compiler (I'm using the CloudFlare-hosted version 2.6.1 running in Safari 9.1.1 (11601.6.17)) and [less2css.org](http://less2css.org/). Specifically, performing a math operation on using a variable with units results in a unit-less answer. Consider the following LESS snippet:

```
@fontSize: 16;
@em: @fontSize * 1em;
header.page h1 {
  font-size: 42 / @em;
}
```

The client-side JavaScript implementation and [less2css.org](http://less2css.org/#%7B%22less%22%3A%22%40fontSize%3A%2016%3B%5Cn%40em%3A%20%40fontSize%20*%201em%3B%5Cnheader.page%20h1%20%7B%5Cn%20%20font-size%3A%2042%20%2F%20%40em%3B%5Cn%7D%22%7D) both compile the above as:

```
header.page h1 {
  font-size: 2.625em;
}
```

But LESSCompile (with default settings—all boxes unchecked and line numbering `off`) strips the units:

```
header.page h1 {
  font-size: 2.625;
}
```

That the math involves a variable doesn't seem to matter; changing the line to `font-size: 42 / 16em;` gives the same result.

The [LESS documentation](http://lesscss.org/features/#features-overview-feature-operations) states that "The result has leftmost explicitly stated unit type," which I interpret as meaning the unit-less `42` operand should be ignored (for the purpose of determining units) and the units of `16em` should be used for the result, giving `2.625em` and not `2.625`.

For clarity: I'm using both the plugin and the client-side JS compiler as a _comparison_ and to guard against the likelihood that the problem lies in my LESS code. I'm _not_ using both at the same time.

**Comment by mjvotaw** [comment]
Can you download the build for 1.2.2 and give it a try?

https://github.com/mjvotaw/Coda-2-LESS-Compiler/releases/tag/v1.2.2

**Comment by Calrion** [comment]
👍 Looks good! My LESS file is now compiling as I expect, and I'm getting the desired results in the browser.

Thanks so much for the quick fix on this, it really is appreciated, and thanks for such a great plugin. I'll leave you to close this issue as you're the maintainer, but as far as I'm concerned it's job done with my thanks.

For the record: LESSCompile is still showing as v1.2.1 in the Coda preferences plugins tab (and in the plugin preferences reports as version 2.2.0, LESS version 1.2.1).
