### ISSUE TITLE
Generate source map

### ISSUE THREAD

**Issue by mountainash** [mjvotaw/Coda-2-LESS-Compiler#26]
If I enable the "Generate Source Map" site preference, the plugin fails to generate a .css or a map file - it stops working. Disabling this option enables the plugin to work as expected.

**Comment by mjvotaw** [comment]
Thanks for bringing this to my attention, I'll try to look at this tonight.

**Comment by schuetz** [comment]
I can confirm this issue. In the last version (1.2.1) source map generation was working, maybe this will help you find the error...

**Comment by mjvotaw** [comment]
Yes, thanks for the info. I was fairly certain it was working in previous versions.

**Comment by mjvotaw** [comment]
Well it looks like the only thing that really changed between 1.2.1 and 1.2.2 was the version of the Less compiler. I've updated it to 2.7.1, will you download and install the link below and let me know if it's working?

[LESSCompile.codaplugin.zip](https://github.com/mjvotaw/Coda-2-LESS-Compiler/files/594997/LESSCompile.codaplugin.zip)


Also, I'm having trouble replicating the issue. It may be that the test css files I'm using are too simple, or missing some common case, but it seems to be generating source maps just fine on 1.2.2. If the above doesn't fix the issue, would one of you mind sending me a copy of the files that are behaving odd?

**Comment by schuetz** [comment]
Unfortunatley, it doesn't seem to work either :-/ ... As soon as I check "Generate source map" (regardless of other options) the css file is no longer being generated. I tried with a single less file with just one style. I'm using Coda 2.5.19 and macOS 10.11.6 if that info helps you...

[LESSCompile-test.zip](https://github.com/mjvotaw/Coda-2-LESS-Compiler/files/595200/LESSCompile-test.zip)

**Comment by mjvotaw** [comment]
Very strange. I'm on basically the same setup (10.11.5 I think), and everything seems to be working for me.
If you turn on verbose logging in Preferences, and open Console, you should see lines that start with "Less Complier: LESS::"  when you try to save a less file. Can you copy those lines for me as well?

**Comment by schuetz** [comment]
Hm, in fact this is strange... Hope the log entries are helpful for you.

[log.zip](https://github.com/mjvotaw/Coda-2-LESS-Compiler/files/595276/log.zip)

**Comment by mjvotaw** [comment]
Hmm, that's.... not as helpful as I'd have liked it to be. I guess that's something else I need to fix.

Looks like it's a dependency issue. I somehow managed to accidentally install a copy of the source-map node module on my machine that was being picked up by Less. In previous versions of Less, they were using a built-in version of this, but around 2.5 or so, they switched to using a different module. I guess I need to figure out why it's not picking up the local copy that is has.

**Comment by mjvotaw** [comment]
Can you give this a try when you get a chance? Thanks for being so quick to respond.

[LESSCompile.codaplugin.zip](https://github.com/mjvotaw/Coda-2-LESS-Compiler/files/595507/LESSCompile.codaplugin.zip)

**Comment by schuetz** [comment]
I just tested it with different settings and files/sites, seems to work now.
Big up anway for building and providing this plugin!

**Comment by mjvotaw** [comment]
I'm just glad people are using it.

**Comment by mountainash** [comment]
Well done! It's fixed. Thanks for looking into this so quickly.
