### ISSUE TITLE
!important optimisation

### ISSUE THREAD

**Issue by mountainash** [mjvotaw/Coda-2-LESS-Compiler#27]
I've noticed that "12px !important" is compressed/minified to "12px!important" on other less compilers. If this rule is used repetitively, having this space removed could save even more precious bytes.

**Comment by mjvotaw** [comment]
I'm using the built-in compression with Less.js. As their documentation notes, "This does an okay job but does not utilise all the tricks of dedicated css compression." 

I could probably incorporate a more aggressive compressor (possibly as a second "aggressive compression" option),if you think that would be helpful. Have you had any experience with any node.js css compressors that you've liked?

**Comment by mountainash** [comment]
I was previously using https://github.com/idmean/CodaLess which is where I noticed these minor but still possible optimisations. But it's just using less minify through https://github.com/less/less-plugin-clean-css which you might also be able to use?

**Comment by mjvotaw** [comment]
Ah, that's perfect. Thanks!
