### ISSUE TITLE
no logging in macOS 10.12.2?

### ISSUE THREAD

**Issue by tmcgill** [mjvotaw/Coda-2-LESS-Compiler#29]
Since upgrading to macOS 10.12.2, I can't seem to find any LESS entries in system.log. Is this just me?

**Comment by mjvotaw** [comment]
I haven't upgraded to 10.12 yet, so I can't confirm yet.

**Comment by tmcgill** [comment]
I installed 10.12 a while ago and experienced no logging issues until yesterday when I updated to 10.12.2, so minor 10.12 releases prior to 10.12.2 may be unaffected.
